platform :ios, '11.0'

# Incluir el script de módulos nativos de React Native
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Configura el uso de frameworks con enlace estático
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'Yaiki' do
  # Configuración de módulos nativos
  config = use_native_modules!

  # Configuración de React Native
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,  # Cambia a false si no utilizas Hermes
    :fabric_enabled => false, # Cambia a true si utilizas la nueva arquitectura
    :flipper_configuration => FlipperConfiguration.disabled  # Deshabilita Flipper
  )

  target 'YaikiTests' do
    inherit! :complete
    # Pods para pruebas
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end